AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - simple pure native function with Quarkus

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Api Gateway for Quarkus demo
      StageName: Test

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Messages
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: MessagePut/target/function.zip
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
      Events:
        SendMessages:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /messages
            Method: POST
  FindAllMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: MessageFindAll/target/function.zip
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
              TableName: !Ref MessagesTable
      Events:
        FetchMessages:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /messages
            Method: GET

Outputs:
  CapitalizeFunction:
    Description: URL for application
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Test/'
    Export:
      Name: CapitalizeFunctionApi
